services:

  eureka:
    build:
      context: ./eureka-server
    image: laflosh/eureka-server
    container_name: eureka-server
    ports:
      - "9101:9101"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9101/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s

  gateway:
    build:
      context: ./gateway-server
    image: laflosh/gateway-server
    container_name: gateway-server
    environment:
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "8080:8080"
    depends_on:
      eureka:
        condition: service_healthy

  mservice-clientui:
    build:
      context: ./mservice-clientui
    image: laflosh/mservice-clientui
    container_name: mservice-clientui
    depends_on:
      eureka:
        condition: service_healthy

  mservice-patient:
    build:
      context: ./mservice-patient
    image: laflosh/mservice-patient
    container_name: mservice-patient
    environment:
      - DB_URL=${DB_PATIENT_URL}
      - DB_USERNAME=${DB_PATIENT_USERNAME}
      - DB_PASSWORD=${DB_PATIENT_PASSWORD}
      - DB_DIALECT=${DB_PATIENT_DIALECT}
    depends_on:
      eureka:
        condition: service_healthy

  mservice-note:
    build:
      context: ./mservice-note
    image: laflosh/mservice-note
    container_name: mservice-note
    environment:
      - DB_HOST=${DB_NOTE_HOST}
      - DB_PORT=${DB_NOTE_PORT}
      - DB_NAME=${DB_NOTE_NAME}
    depends_on:
      eureka:
        condition: service_healthy

  mservice-risk:
    build:
      context: ./mservice-risk
    image: laflosh/mservice-risk
    container_name: mservice-risk
    depends_on:
      eureka:
        condition: service_healthy

  mservice-user:
    build:
      context: ./mservice-user
    image: laflosh/mservice-user
    container_name: mservice-user
    environment:
      - DB_URL=${DB_USER_URL}
      - DB_USERNAME=${DB_USER_USERNAME}
      - DB_PASSWORD=${DB_USER_PASSWORD}
      - DB_DIALECT=${DB_USER_DIALECT}
    depends_on:
      eureka:
        condition: service_healthy