services:

  eureka:
    build:
      context: ./eureka-server
    image: laflosh/eureka-server
    container_name: eureka-server
    ports:
      - "9101:9101"
    healthcheck:
      test: curl --fail --silent http://localhost:9101/eureka || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s

  gateway:
    build:
      context: ./gateway-server
    image: laflosh/gateway-server
    container_name: gateway-server
    environment:
      - SECRET_KEY=D3B714FD8A478B9BD63E869F6EF839D7DE4989431FAFECCD32CBE486C7
    ports:
      - "8080:8080"
    depends_on:
      eureka:
        condition: service_healthy

  mservice-clientui:
    build:
      context: ./mservice-clientui
    image: laflosh/mservice-clientui
    container_name: mservice-clientui
    ports:
      - "9001:9001"
    depends_on:
      gateway:
        condition: service_started

  mservice-patient:
    build:
      context: ./mservice-patient
    image: laflosh/mservice-patient
    container_name: mservice-patient
    environment:
      - DB_URL=jdbc:mysql://mysql:3306/mservice-patient?serverTimezone=UTC
      - DB_USERNAME=root
      - DB_PASSWORD=
      - DB_DIALECT=org.hibernate.dialect.MySQL8Dialect
    ports:
      - "9002:9002"
    depends_on:
      mysql:
        condition: service_started
      eureka:
        condition: service_healthy

  mservice-note:
    build:
      context: ./mservice-note
    image: laflosh/mservice-note
    container_name: mservice-note
    environment:
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=mservice-note
    ports:
      - "9003:9003"
    depends_on:
      mongo:
        condition: service_started
      eureka:
        condition: service_healthy

  mservice-risk:
    build:
      context: ./mservice-risk
    image: laflosh/mservice-risk
    container_name: mservice-risk
    ports:
      - "9005:9005"
    depends_on:
      gateway:
        condition: service_started
      eureka:
        condition: service_healthy

  mservice-user:
    build:
      context: ./mservice-user
    image: laflosh/mservice-user
    container_name: mservice-user
    environment:
      - DB_URL=jdbc:mysql://mysql:3306/mservice-user?serverTimezone=UTC
      - DB_USERNAME=root
      - DB_PASSWORD=
      - DB_DIALECT=org.hibernate.dialect.MySQL8Dialect
    ports:
      - "9004:9004"
    depends_on:
      mysql:
        condition: service_started
      eureka:
        condition: service_healthy

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mysql-data:
  mongo-data: